name: Sync to Adobe Git

on:
  push:
    branches: ["main", "develop", "feature/*"]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Adobe Git remote 
        run: |
          if git remote | grep -q adobe; then
            echo "Adobe remote already exists."
          else
            git remote add adobe https://${{secrets.ADOBE_UN}}:${{secrets.ADOBE_PASS}}@git.cloudmanager.adobe.com/munvopartnersandbox/github-sync/
          fi
          git fetch adobe

      - name: Determine current branch and push to Adobe Git
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$BRANCH" == "develop" || "$BRANCH" == "main" || "$BRANCH" =~ ^feature/.* ]]; then
            git push adobe $BRANCH
            echo "✅ Successfully pushed $BRANCH to Adobe Git"
          else
            echo "⏭ Skipping sync for branch: $BRANCH"
          fi
