name: run pipeline

on:
  push:
    branches: ["main", "develop"]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To fetch all history for the branch

      - name: Authenticate with Adobe I/O
        uses: adobe/aio-apps-action@3.4.0
        id: auth
        with:
          command: oauth_sts
          clientid: ${{ secrets.ADOBE_CLIENTID }}
          clientsecret: ${{ secrets.ADOBE_CLIENTSECRET }}
          technicalaccountid: ${{ secrets.ADOBE_TECHNICALACCOUNTID }}
          technicalaccountemail: ${{ secrets.ADOBE_TECHNICALEMAIL }}
          imsorgid: ${{ secrets.ADOBE_IMSORGID }}
          scopes: 'ent_cloudmgr, openid, AdobeID, read_organizations, additional_info.projectedProductContext, read_pc.dma_aem_ams'

      - name: Create Execution
        uses: adobe/aio-cloudmanager-create-execution-action@v1.2.0
        with:
          PIPELINEID: ${{ secrets.ADOBE_PIPELINEID }}
          PROGRAMID: ${{ secrets.ADOBE_PROGRAMID }}
          IMSORGID: ${{ secrets.ADOBE_IMSORGID }}
