name: Sync to Adobe Git

on:
  push:
    branches: ["main", "develop"]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To fetch all history for the branch

      - name: Authenticate with Adobe I/O
        uses: adobe/aio-apps-action@3.4.0
        id: auth
        with:
          command: oauth_sts
          clientid: ${{ secrets.ADOBE_CLIENTID }}
          clientsecret: ${{ secrets.ADOBE_CLIENTSECRET }}
          technicalaccountid: ${{ secrets.ADOBE_TECHNICALACCOUNTID }}
          technicalaccountemail: ${{ secrets.ADOBE_TECHNICALEMAIL }}
          imsorgid: ${{ secrets.ADOBE_IMSORGID }}
          scopes: 'ent_cloudmgr, openid, AdobeID, read_organizations, additional_info.projectedProductContext, read_pc.dma_aem_ams'
         

      - name: Output OAuth Token for Debugging
        run: |
          echo "OAuth Token: ${{ steps.auth.outputs.token }}"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Adobe Git remote if not exists
        run: |
          OAUTH_TOKEN="${{ steps.auth.outputs.token }}"
          git remote add adobe https://oauth2:${OAUTH_TOKEN}@git.cloudmanager.adobe.com/munvopartnersandbox/github-sync/

      - name: Determine current branch and push to Adobe Git
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$BRANCH" == "develop" || "$BRANCH" == "main" ]]; then
            git push adobe $BRANCH
            echo "✅ Successfully pushed $BRANCH to Adobe Git "
          else
            echo "⏭ Skipping sync for branch: $BRANCH"
          fi
